# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rover_v3.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1133, 817)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(0, 255, 237, 69), stop:0.426471 rgba(0, 214, 138, 69), stop:0.441176 rgba(0, 255, 246, 145), stop:0.534314 rgba(255, 255, 0, 135), stop:0.57754 rgba(0, 201, 255, 130), stop:0.70098 rgba(0, 178, 171, 208), stop:0.779412 rgba(255, 218, 71, 130), stop:1 rgba(0, 237, 255, 69));")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1109, 752))
        self.scrollAreaWidgetContents_2.setStyleSheet("background-color:transparent;")
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.TopLayout = QtWidgets.QHBoxLayout()
        self.TopLayout.setObjectName("TopLayout")
        self.title = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(28)
        self.title.setFont(font)
        self.title.setStyleSheet("background-color: rgb(255, 255, 255,80%);")
        self.title.setObjectName("title")
        self.TopLayout.addWidget(self.title)
        self.warring = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(28)
        self.warring.setFont(font)
        self.warring.setStyleSheet("background-color: rgb(255, 239, 57);\n"
"")
        self.warring.setAlignment(QtCore.Qt.AlignCenter)
        self.warring.setObjectName("warring")
        self.TopLayout.addWidget(self.warring)
        self.OnOffBtnLayout = QtWidgets.QHBoxLayout()
        self.OnOffBtnLayout.setObjectName("OnOffBtnLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.RoverMainOnOffBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.RoverMainOnOffBtn.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.RoverMainOnOffBtn.setObjectName("RoverMainOnOffBtn")
        self.verticalLayout.addWidget(self.RoverMainOnOffBtn)
        self.VisionOnOffBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.VisionOnOffBtn.setStyleSheet("background-color: rgb(255, 3, 3);")
        self.VisionOnOffBtn.setObjectName("VisionOnOffBtn")
        self.verticalLayout.addWidget(self.VisionOnOffBtn)
        self.OnOffBtnLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.LidarOnOffBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.LidarOnOffBtn.setStyleSheet("background-color: rgb(255, 3, 3);")
        self.LidarOnOffBtn.setObjectName("LidarOnOffBtn")
        self.verticalLayout_3.addWidget(self.LidarOnOffBtn)
        self.AlgorithmOnOffBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.AlgorithmOnOffBtn.setStyleSheet("background-color: rgb(255, 3, 3);")
        self.AlgorithmOnOffBtn.setObjectName("AlgorithmOnOffBtn")
        self.verticalLayout_3.addWidget(self.AlgorithmOnOffBtn)
        self.OnOffBtnLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.OnOffBtnLayout.addLayout(self.verticalLayout_2)
        self.StopAllBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StopAllBtn.sizePolicy().hasHeightForWidth())
        self.StopAllBtn.setSizePolicy(sizePolicy)
        self.StopAllBtn.setStyleSheet("background-color: rgb(255, 3, 3);")
        self.StopAllBtn.setObjectName("StopAllBtn")
        self.OnOffBtnLayout.addWidget(self.StopAllBtn)
        self.TopLayout.addLayout(self.OnOffBtnLayout)
        self.verticalLayout_6.addLayout(self.TopLayout)
        self.MessageBox_Edit = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MessageBox_Edit.sizePolicy().hasHeightForWidth())
        self.MessageBox_Edit.setSizePolicy(sizePolicy)
        self.MessageBox_Edit.setMinimumSize(QtCore.QSize(0, 25))
        self.MessageBox_Edit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.MessageBox_Edit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.MessageBox_Edit.setObjectName("MessageBox_Edit")
        self.verticalLayout_6.addWidget(self.MessageBox_Edit)
        self.MiddleLayout = QtWidgets.QHBoxLayout()
        self.MiddleLayout.setObjectName("MiddleLayout")
        self.ControlPattel = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ControlPattel.sizePolicy().hasHeightForWidth())
        self.ControlPattel.setSizePolicy(sizePolicy)
        self.ControlPattel.setObjectName("ControlPattel")
        self.FunctionBtnLayout = QtWidgets.QVBoxLayout(self.ControlPattel)
        self.FunctionBtnLayout.setObjectName("FunctionBtnLayout")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_5 = QtWidgets.QLabel(self.ControlPattel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_9.addWidget(self.label_5)
        self.LidarUSB_text = QtWidgets.QTextEdit(self.ControlPattel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LidarUSB_text.sizePolicy().hasHeightForWidth())
        self.LidarUSB_text.setSizePolicy(sizePolicy)
        self.LidarUSB_text.setMaximumSize(QtCore.QSize(180, 60))
        self.LidarUSB_text.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.LidarUSB_text.setObjectName("LidarUSB_text")
        self.horizontalLayout_9.addWidget(self.LidarUSB_text)
        self.verticalLayout_13.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.ControlPattel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.VisionStatus_text = QtWidgets.QTextEdit(self.ControlPattel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VisionStatus_text.sizePolicy().hasHeightForWidth())
        self.VisionStatus_text.setSizePolicy(sizePolicy)
        self.VisionStatus_text.setMaximumSize(QtCore.QSize(180, 25))
        self.VisionStatus_text.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.VisionStatus_text.setObjectName("VisionStatus_text")
        self.horizontalLayout_5.addWidget(self.VisionStatus_text)
        self.verticalLayout_13.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_4 = QtWidgets.QLabel(self.ControlPattel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_8.addWidget(self.label_4)
        self.VisionData_text = QtWidgets.QTextEdit(self.ControlPattel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VisionData_text.sizePolicy().hasHeightForWidth())
        self.VisionData_text.setSizePolicy(sizePolicy)
        self.VisionData_text.setMaximumSize(QtCore.QSize(180, 25))
        self.VisionData_text.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.VisionData_text.setObjectName("VisionData_text")
        self.horizontalLayout_8.addWidget(self.VisionData_text)
        self.verticalLayout_13.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_6 = QtWidgets.QLabel(self.ControlPattel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_11.addWidget(self.label_6)
        self.CurrentSpeed_text = QtWidgets.QTextEdit(self.ControlPattel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CurrentSpeed_text.sizePolicy().hasHeightForWidth())
        self.CurrentSpeed_text.setSizePolicy(sizePolicy)
        self.CurrentSpeed_text.setMaximumSize(QtCore.QSize(180, 25))
        self.CurrentSpeed_text.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.CurrentSpeed_text.setObjectName("CurrentSpeed_text")
        self.horizontalLayout_11.addWidget(self.CurrentSpeed_text)
        self.verticalLayout_13.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_16 = QtWidgets.QLabel(self.ControlPattel)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_20.addWidget(self.label_16)
        self.line_pp_time = QtWidgets.QLineEdit(self.ControlPattel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_pp_time.sizePolicy().hasHeightForWidth())
        self.line_pp_time.setSizePolicy(sizePolicy)
        self.line_pp_time.setMaximumSize(QtCore.QSize(180, 40))
        self.line_pp_time.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_pp_time.setObjectName("line_pp_time")
        self.horizontalLayout_20.addWidget(self.line_pp_time)
        self.verticalLayout_13.addLayout(self.horizontalLayout_20)
        self.FunctionBtnLayout.addLayout(self.verticalLayout_13)
        self.groupBox = QtWidgets.QGroupBox(self.ControlPattel)
        self.groupBox.setStyleSheet("background-color: rgba(255, 255, 255, 100);")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.slider_steer = QtWidgets.QSlider(self.groupBox)
        self.slider_steer.setMinimum(315)
        self.slider_steer.setMaximum(495)
        self.slider_steer.setProperty("value", 400)
        self.slider_steer.setOrientation(QtCore.Qt.Horizontal)
        self.slider_steer.setInvertedAppearance(True)
        self.slider_steer.setObjectName("slider_steer")
        self.verticalLayout_24.addWidget(self.slider_steer)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.slider_speed = QtWidgets.QSlider(self.groupBox)
        self.slider_speed.setMinimum(310)
        self.slider_speed.setMaximum(490)
        self.slider_speed.setSingleStep(1)
        self.slider_speed.setProperty("value", 400)
        self.slider_speed.setOrientation(QtCore.Qt.Vertical)
        self.slider_speed.setObjectName("slider_speed")
        self.horizontalLayout_17.addWidget(self.slider_speed)
        self.verticalLayout_24.addLayout(self.horizontalLayout_17)
        self.FunctionBtnLayout.addWidget(self.groupBox)
        self.MiddleLayout.addWidget(self.ControlPattel)
        self.toolBox = QtWidgets.QToolBox(self.scrollAreaWidgetContents_2)
        self.toolBox.setMinimumSize(QtCore.QSize(350, 0))
        self.toolBox.setMaximumSize(QtCore.QSize(350, 16777215))
        font = QtGui.QFont()
        font.setFamily("UD Digi Kyokasho NP-B")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.toolBox.setFont(font)
        self.toolBox.setStyleSheet("\n"
"background-color: rgb(0, 0, 0,5%);")
        self.toolBox.setFrameShape(QtWidgets.QFrame.Box)
        self.toolBox.setLineWidth(3)
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, -8, 323, 432))
        self.page.setObjectName("page")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.keyboardcontrol_frame = QtWidgets.QFrame(self.page)
        self.keyboardcontrol_frame.setStyleSheet("")
        self.keyboardcontrol_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.keyboardcontrol_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.keyboardcontrol_frame.setLineWidth(1)
        self.keyboardcontrol_frame.setMidLineWidth(0)
        self.keyboardcontrol_frame.setObjectName("keyboardcontrol_frame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.keyboardcontrol_frame)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.KeyboardControlBtn = QtWidgets.QPushButton(self.keyboardcontrol_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.KeyboardControlBtn.sizePolicy().hasHeightForWidth())
        self.KeyboardControlBtn.setSizePolicy(sizePolicy)
        self.KeyboardControlBtn.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.KeyboardControlBtn.setFont(font)
        self.KeyboardControlBtn.setStyleSheet("background-color: rgb(112, 155, 255);")
        self.KeyboardControlBtn.setObjectName("KeyboardControlBtn")
        self.verticalLayout_12.addWidget(self.KeyboardControlBtn)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.KeyboardControl_SetSpeedBtn = QtWidgets.QPushButton(self.keyboardcontrol_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.KeyboardControl_SetSpeedBtn.sizePolicy().hasHeightForWidth())
        self.KeyboardControl_SetSpeedBtn.setSizePolicy(sizePolicy)
        self.KeyboardControl_SetSpeedBtn.setStyleSheet("background-color: rgb(227, 227, 227);")
        self.KeyboardControl_SetSpeedBtn.setObjectName("KeyboardControl_SetSpeedBtn")
        self.horizontalLayout_10.addWidget(self.KeyboardControl_SetSpeedBtn)
        self.KeyBoardControl_speed = QtWidgets.QSlider(self.keyboardcontrol_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.KeyBoardControl_speed.sizePolicy().hasHeightForWidth())
        self.KeyBoardControl_speed.setSizePolicy(sizePolicy)
        self.KeyBoardControl_speed.setMaximum(100)
        self.KeyBoardControl_speed.setProperty("value", 1)
        self.KeyBoardControl_speed.setOrientation(QtCore.Qt.Horizontal)
        self.KeyBoardControl_speed.setObjectName("KeyBoardControl_speed")
        self.horizontalLayout_10.addWidget(self.KeyBoardControl_speed)
        self.SetSpeed_label = QtWidgets.QLabel(self.keyboardcontrol_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SetSpeed_label.sizePolicy().hasHeightForWidth())
        self.SetSpeed_label.setSizePolicy(sizePolicy)
        self.SetSpeed_label.setObjectName("SetSpeed_label")
        self.horizontalLayout_10.addWidget(self.SetSpeed_label)
        self.verticalLayout_12.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_7.addLayout(self.verticalLayout_12)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setContentsMargins(-1, -1, 0, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.KeyRight = QtWidgets.QGraphicsView(self.keyboardcontrol_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.KeyRight.sizePolicy().hasHeightForWidth())
        self.KeyRight.setSizePolicy(sizePolicy)
        self.KeyRight.setMaximumSize(QtCore.QSize(20, 20))
        self.KeyRight.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.KeyRight.setObjectName("KeyRight")
        self.gridLayout.addWidget(self.KeyRight, 1, 2, 1, 1)
        self.KeyDown = QtWidgets.QGraphicsView(self.keyboardcontrol_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.KeyDown.sizePolicy().hasHeightForWidth())
        self.KeyDown.setSizePolicy(sizePolicy)
        self.KeyDown.setMaximumSize(QtCore.QSize(20, 20))
        self.KeyDown.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.KeyDown.setObjectName("KeyDown")
        self.gridLayout.addWidget(self.KeyDown, 1, 1, 1, 1)
        self.KeyUp = QtWidgets.QGraphicsView(self.keyboardcontrol_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.KeyUp.sizePolicy().hasHeightForWidth())
        self.KeyUp.setSizePolicy(sizePolicy)
        self.KeyUp.setMaximumSize(QtCore.QSize(20, 20))
        self.KeyUp.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.KeyUp.setObjectName("KeyUp")
        self.gridLayout.addWidget(self.KeyUp, 0, 1, 1, 1)
        self.KeyLeft = QtWidgets.QGraphicsView(self.keyboardcontrol_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.KeyLeft.sizePolicy().hasHeightForWidth())
        self.KeyLeft.setSizePolicy(sizePolicy)
        self.KeyLeft.setMaximumSize(QtCore.QSize(20, 20))
        self.KeyLeft.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.KeyLeft.setObjectName("KeyLeft")
        self.gridLayout.addWidget(self.KeyLeft, 1, 0, 1, 1)
        self.horizontalLayout_7.addLayout(self.gridLayout)
        self.verticalLayout_15.addWidget(self.keyboardcontrol_frame)
        self.ShowMapFrame = QtWidgets.QFrame(self.page)
        self.ShowMapFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.ShowMapFrame.setLineWidth(1)
        self.ShowMapFrame.setObjectName("ShowMapFrame")
        self.ShowMapLayout = QtWidgets.QVBoxLayout(self.ShowMapFrame)
        self.ShowMapLayout.setObjectName("ShowMapLayout")
        self.ShowMapBtn = QtWidgets.QPushButton(self.ShowMapFrame)
        self.ShowMapBtn.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(11)
        self.ShowMapBtn.setFont(font)
        self.ShowMapBtn.setStyleSheet("background-color: rgb(112, 155, 255);\n"
"\n"
"\n"
"")
        self.ShowMapBtn.setObjectName("ShowMapBtn")
        self.ShowMapLayout.addWidget(self.ShowMapBtn)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ShowMap_AddBtn = QtWidgets.QPushButton(self.ShowMapFrame)
        self.ShowMap_AddBtn.setStyleSheet("background-color: rgb(229, 229, 229);")
        self.ShowMap_AddBtn.setObjectName("ShowMap_AddBtn")
        self.horizontalLayout_2.addWidget(self.ShowMap_AddBtn)
        self.ShowMap_DelBtn = QtWidgets.QPushButton(self.ShowMapFrame)
        self.ShowMap_DelBtn.setStyleSheet("background-color: rgb(229, 229, 229);")
        self.ShowMap_DelBtn.setObjectName("ShowMap_DelBtn")
        self.horizontalLayout_2.addWidget(self.ShowMap_DelBtn)
        self.ShowMapLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_15.addWidget(self.ShowMapFrame)
        self.SaveImportMap = QtWidgets.QFrame(self.page)
        self.SaveImportMap.setFrameShape(QtWidgets.QFrame.Box)
        self.SaveImportMap.setLineWidth(1)
        self.SaveImportMap.setObjectName("SaveImportMap")
        self.SaveMap = QtWidgets.QHBoxLayout(self.SaveImportMap)
        self.SaveMap.setObjectName("SaveMap")
        self.SaveMapBtn = QtWidgets.QPushButton(self.SaveImportMap)
        self.SaveMapBtn.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.SaveMapBtn.setFont(font)
        self.SaveMapBtn.setStyleSheet("background-color: rgb(112, 155, 255);")
        self.SaveMapBtn.setObjectName("SaveMapBtn")
        self.SaveMap.addWidget(self.SaveMapBtn)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.ImportMapBtn = QtWidgets.QPushButton(self.SaveImportMap)
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(11)
        self.ImportMapBtn.setFont(font)
        self.ImportMapBtn.setStyleSheet("background-color: rgb(112, 155, 255);")
        self.ImportMapBtn.setObjectName("ImportMapBtn")
        self.verticalLayout_11.addWidget(self.ImportMapBtn)
        self.SaveMap.addLayout(self.verticalLayout_11)
        self.verticalLayout_15.addWidget(self.SaveImportMap)
        self.WayPointFrame = QtWidgets.QFrame(self.page)
        self.WayPointFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.WayPointFrame.setLineWidth(1)
        self.WayPointFrame.setObjectName("WayPointFrame")
        self.WayPoints = QtWidgets.QHBoxLayout(self.WayPointFrame)
        self.WayPoints.setObjectName("WayPoints")
        self.WayPointsBtn = QtWidgets.QPushButton(self.WayPointFrame)
        self.WayPointsBtn.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.WayPointsBtn.setFont(font)
        self.WayPointsBtn.setStyleSheet("background-color: rgb(112, 155, 255);")
        self.WayPointsBtn.setObjectName("WayPointsBtn")
        self.WayPoints.addWidget(self.WayPointsBtn)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.AddWayPointBtn = QtWidgets.QPushButton(self.WayPointFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddWayPointBtn.sizePolicy().hasHeightForWidth())
        self.AddWayPointBtn.setSizePolicy(sizePolicy)
        self.AddWayPointBtn.setStyleSheet("background-color: rgb(227, 227, 227);\n"
"border-color: rgb(0, 0, 0);")
        self.AddWayPointBtn.setObjectName("AddWayPointBtn")
        self.horizontalLayout.addWidget(self.AddWayPointBtn)
        self.DeleteWayPointBtn = QtWidgets.QPushButton(self.WayPointFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DeleteWayPointBtn.sizePolicy().hasHeightForWidth())
        self.DeleteWayPointBtn.setSizePolicy(sizePolicy)
        self.DeleteWayPointBtn.setStyleSheet("background-color: rgb(227, 227, 227);\n"
"border-color: rgb(0, 0, 0);")
        self.DeleteWayPointBtn.setObjectName("DeleteWayPointBtn")
        self.horizontalLayout.addWidget(self.DeleteWayPointBtn)
        self.verticalLayout_8.addLayout(self.horizontalLayout)
        self.WayPointList = QtWidgets.QLineEdit(self.WayPointFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WayPointList.sizePolicy().hasHeightForWidth())
        self.WayPointList.setSizePolicy(sizePolicy)
        self.WayPointList.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.WayPointList.setObjectName("WayPointList")
        self.verticalLayout_8.addWidget(self.WayPointList)
        self.WayPoints.addLayout(self.verticalLayout_8)
        self.verticalLayout_15.addWidget(self.WayPointFrame)
        self.CalibrationMapFrame = QtWidgets.QFrame(self.page)
        self.CalibrationMapFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.CalibrationMapFrame.setLineWidth(1)
        self.CalibrationMapFrame.setObjectName("CalibrationMapFrame")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.CalibrationMapFrame)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.CalibrationBtn = QtWidgets.QPushButton(self.CalibrationMapFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CalibrationBtn.sizePolicy().hasHeightForWidth())
        self.CalibrationBtn.setSizePolicy(sizePolicy)
        self.CalibrationBtn.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.CalibrationBtn.setFont(font)
        self.CalibrationBtn.setStyleSheet("background-color: rgb(112, 155, 255);")
        self.CalibrationBtn.setObjectName("CalibrationBtn")
        self.horizontalLayout_12.addWidget(self.CalibrationBtn)
        self.verticalLayout_15.addWidget(self.CalibrationMapFrame)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem)
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 344, 424))
        self.page_2.setObjectName("page_2")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.VisionBuildMapFrame = QtWidgets.QFrame(self.page_2)
        self.VisionBuildMapFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.VisionBuildMapFrame.setLineWidth(1)
        self.VisionBuildMapFrame.setObjectName("VisionBuildMapFrame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.VisionBuildMapFrame)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.VisionBuildMapBtn = QtWidgets.QPushButton(self.VisionBuildMapFrame)
        self.VisionBuildMapBtn.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.VisionBuildMapBtn.setFont(font)
        self.VisionBuildMapBtn.setStyleSheet("background-color: rgb(112, 155, 255);")
        self.VisionBuildMapBtn.setObjectName("VisionBuildMapBtn")
        self.verticalLayout_14.addWidget(self.VisionBuildMapBtn)
        self.pushButton = QtWidgets.QPushButton(self.VisionBuildMapFrame)
        self.pushButton.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_14.addWidget(self.pushButton)
        self.horizontalLayout_6.addLayout(self.verticalLayout_14)
        self.VisionBuildMap = QtWidgets.QVBoxLayout()
        self.VisionBuildMap.setObjectName("VisionBuildMap")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.VisionBuildMapFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255,80%);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.BuildMapID = QtWidgets.QSpinBox(self.VisionBuildMapFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BuildMapID.sizePolicy().hasHeightForWidth())
        self.BuildMapID.setSizePolicy(sizePolicy)
        self.BuildMapID.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.BuildMapID.setProperty("value", 1)
        self.BuildMapID.setObjectName("BuildMapID")
        self.horizontalLayout_3.addWidget(self.BuildMapID)
        self.VisionBuildMap.addLayout(self.horizontalLayout_3)
        self.VisionBuildMapStopBtn = QtWidgets.QPushButton(self.VisionBuildMapFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VisionBuildMapStopBtn.sizePolicy().hasHeightForWidth())
        self.VisionBuildMapStopBtn.setSizePolicy(sizePolicy)
        self.VisionBuildMapStopBtn.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.VisionBuildMapStopBtn.setObjectName("VisionBuildMapStopBtn")
        self.VisionBuildMap.addWidget(self.VisionBuildMapStopBtn)
        self.horizontalLayout_6.addLayout(self.VisionBuildMap)
        self.verticalLayout_16.addWidget(self.VisionBuildMapFrame)
        self.VisionUseMapFrame = QtWidgets.QFrame(self.page_2)
        self.VisionUseMapFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.VisionUseMapFrame.setLineWidth(1)
        self.VisionUseMapFrame.setObjectName("VisionUseMapFrame")
        self.VisionUseMap = QtWidgets.QHBoxLayout(self.VisionUseMapFrame)
        self.VisionUseMap.setObjectName("VisionUseMap")
        self.VisionUseMapBtn = QtWidgets.QPushButton(self.VisionUseMapFrame)
        self.VisionUseMapBtn.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.VisionUseMapBtn.setFont(font)
        self.VisionUseMapBtn.setStyleSheet("background-color: rgb(112, 155, 255);")
        self.VisionUseMapBtn.setObjectName("VisionUseMapBtn")
        self.VisionUseMap.addWidget(self.VisionUseMapBtn)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.VisionUseMapFrame)
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255,80%);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.UseMapID = QtWidgets.QSpinBox(self.VisionUseMapFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UseMapID.sizePolicy().hasHeightForWidth())
        self.UseMapID.setSizePolicy(sizePolicy)
        self.UseMapID.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.UseMapID.setProperty("value", 1)
        self.UseMapID.setObjectName("UseMapID")
        self.horizontalLayout_4.addWidget(self.UseMapID)
        self.verticalLayout_10.addLayout(self.horizontalLayout_4)
        self.VisionUseMapStopBtn = QtWidgets.QPushButton(self.VisionUseMapFrame)
        self.VisionUseMapStopBtn.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.VisionUseMapStopBtn.setObjectName("VisionUseMapStopBtn")
        self.verticalLayout_10.addWidget(self.VisionUseMapStopBtn)
        self.VisionUseMap.addLayout(self.verticalLayout_10)
        self.verticalLayout_16.addWidget(self.VisionUseMapFrame)
        self.pushButton_2 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_2.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_16.addWidget(self.pushButton_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem1)
        self.toolBox.addItem(self.page_2, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_10 = QtWidgets.QLabel(self.page_3)
        self.label_10.setStyleSheet("background-color: rgba(255, 255, 255, 200);")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_21.addWidget(self.label_10)
        self.label_9 = QtWidgets.QLabel(self.page_3)
        self.label_9.setStyleSheet("background-color: rgba(255, 255, 255, 200);")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_21.addWidget(self.label_9)
        self.horizontalLayout_14.addLayout(self.verticalLayout_21)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.spin_lidar_max = QtWidgets.QSpinBox(self.page_3)
        self.spin_lidar_max.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spin_lidar_max.setMaximum(10000)
        self.spin_lidar_max.setObjectName("spin_lidar_max")
        self.verticalLayout_22.addWidget(self.spin_lidar_max)
        self.spin_lidar_min = QtWidgets.QSpinBox(self.page_3)
        self.spin_lidar_min.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spin_lidar_min.setMaximum(10000)
        self.spin_lidar_min.setObjectName("spin_lidar_min")
        self.verticalLayout_22.addWidget(self.spin_lidar_min)
        self.horizontalLayout_14.addLayout(self.verticalLayout_22)
        self.btn_set_lidar_radius = QtWidgets.QPushButton(self.page_3)
        self.btn_set_lidar_radius.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.btn_set_lidar_radius.setObjectName("btn_set_lidar_radius")
        self.horizontalLayout_14.addWidget(self.btn_set_lidar_radius)
        self.verticalLayout_18.addLayout(self.horizontalLayout_14)
        self.verticalLayout_20.addLayout(self.verticalLayout_18)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_20.addItem(spacerItem2)
        self.toolBox.addItem(self.page_3, "")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout()
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.label_13 = QtWidgets.QLabel(self.page_4)
        self.label_13.setStyleSheet("background-color: rgba(255, 255, 255, 200);")
        self.label_13.setObjectName("label_13")
        self.verticalLayout_26.addWidget(self.label_13)
        self.label_12 = QtWidgets.QLabel(self.page_4)
        self.label_12.setStyleSheet("background-color: rgba(255, 255, 255, 200);")
        self.label_12.setObjectName("label_12")
        self.verticalLayout_26.addWidget(self.label_12)
        self.horizontalLayout_18.addLayout(self.verticalLayout_26)
        self.verticalLayout_27 = QtWidgets.QVBoxLayout()
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.spin_end_x = QtWidgets.QSpinBox(self.page_4)
        self.spin_end_x.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spin_end_x.setMinimum(-50000)
        self.spin_end_x.setMaximum(50000)
        self.spin_end_x.setObjectName("spin_end_x")
        self.verticalLayout_27.addWidget(self.spin_end_x)
        self.spin_end_y = QtWidgets.QSpinBox(self.page_4)
        self.spin_end_y.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spin_end_y.setMinimum(-50000)
        self.spin_end_y.setMaximum(50000)
        self.spin_end_y.setObjectName("spin_end_y")
        self.verticalLayout_27.addWidget(self.spin_end_y)
        self.horizontalLayout_18.addLayout(self.verticalLayout_27)
        self.btn_set_end = QtWidgets.QPushButton(self.page_4)
        self.btn_set_end.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.btn_set_end.setObjectName("btn_set_end")
        self.horizontalLayout_18.addWidget(self.btn_set_end)
        self.verticalLayout_25.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout()
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.label_15 = QtWidgets.QLabel(self.page_4)
        self.label_15.setStyleSheet("background-color: rgba(255, 255, 255, 200);")
        self.label_15.setObjectName("label_15")
        self.verticalLayout_28.addWidget(self.label_15)
        self.label_14 = QtWidgets.QLabel(self.page_4)
        self.label_14.setStyleSheet("background-color: rgba(255, 255, 255, 200);")
        self.label_14.setObjectName("label_14")
        self.verticalLayout_28.addWidget(self.label_14)
        self.horizontalLayout_19.addLayout(self.verticalLayout_28)
        self.verticalLayout_29 = QtWidgets.QVBoxLayout()
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.spin_rover_size = QtWidgets.QSpinBox(self.page_4)
        self.spin_rover_size.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spin_rover_size.setMinimum(1)
        self.spin_rover_size.setMaximum(200)
        self.spin_rover_size.setSingleStep(1)
        self.spin_rover_size.setProperty("value", 20)
        self.spin_rover_size.setObjectName("spin_rover_size")
        self.verticalLayout_29.addWidget(self.spin_rover_size)
        self.spin_unit_step = QtWidgets.QSpinBox(self.page_4)
        self.spin_unit_step.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spin_unit_step.setMinimum(1)
        self.spin_unit_step.setMaximum(400)
        self.spin_unit_step.setProperty("value", 30)
        self.spin_unit_step.setObjectName("spin_unit_step")
        self.verticalLayout_29.addWidget(self.spin_unit_step)
        self.horizontalLayout_19.addLayout(self.verticalLayout_29)
        self.btn_set_as = QtWidgets.QPushButton(self.page_4)
        self.btn_set_as.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.btn_set_as.setObjectName("btn_set_as")
        self.horizontalLayout_19.addWidget(self.btn_set_as)
        self.verticalLayout_25.addLayout(self.horizontalLayout_19)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_25.addItem(spacerItem3)
        self.toolBox.addItem(self.page_4, "")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_11 = QtWidgets.QLabel(self.page_5)
        self.label_11.setStyleSheet("background-color: rgba(255, 255, 255, 200);")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_15.addWidget(self.label_11)
        self.dspin_pt_e_gain = QtWidgets.QDoubleSpinBox(self.page_5)
        self.dspin_pt_e_gain.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dspin_pt_e_gain.setMinimum(-10000.0)
        self.dspin_pt_e_gain.setMaximum(10000.0)
        self.dspin_pt_e_gain.setProperty("value", 1.0)
        self.dspin_pt_e_gain.setObjectName("dspin_pt_e_gain")
        self.horizontalLayout_15.addWidget(self.dspin_pt_e_gain)
        self.btn_pp_gain = QtWidgets.QPushButton(self.page_5)
        self.btn_pp_gain.setObjectName("btn_pp_gain")
        self.horizontalLayout_15.addWidget(self.btn_pp_gain)
        self.verticalLayout_23.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_22 = QtWidgets.QLabel(self.page_5)
        self.label_22.setStyleSheet("background-color: rgba(255, 255, 255, 200);")
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_26.addWidget(self.label_22)
        self.dspin_pt_d_gain = QtWidgets.QDoubleSpinBox(self.page_5)
        self.dspin_pt_d_gain.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dspin_pt_d_gain.setMinimum(0.0)
        self.dspin_pt_d_gain.setMaximum(10000.0)
        self.dspin_pt_d_gain.setProperty("value", 1.0)
        self.dspin_pt_d_gain.setObjectName("dspin_pt_d_gain")
        self.horizontalLayout_26.addWidget(self.dspin_pt_d_gain)
        self.pushButton_3 = QtWidgets.QPushButton(self.page_5)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_26.addWidget(self.pushButton_3)
        self.verticalLayout_23.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_17 = QtWidgets.QLabel(self.page_5)
        self.label_17.setStyleSheet("background-color: rgba(255, 255, 255, 200);")
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_21.addWidget(self.label_17)
        self.lcd_target_steer = QtWidgets.QLCDNumber(self.page_5)
        self.lcd_target_steer.setDigitCount(7)
        self.lcd_target_steer.setObjectName("lcd_target_steer")
        self.horizontalLayout_21.addWidget(self.lcd_target_steer)
        self.verticalLayout_23.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_21 = QtWidgets.QLabel(self.page_5)
        self.label_21.setStyleSheet("background-color: rgba(255, 255, 255, 200);")
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_25.addWidget(self.label_21)
        self.lcd_global_steer = QtWidgets.QLCDNumber(self.page_5)
        self.lcd_global_steer.setDigitCount(7)
        self.lcd_global_steer.setObjectName("lcd_global_steer")
        self.horizontalLayout_25.addWidget(self.lcd_global_steer)
        self.verticalLayout_23.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_20 = QtWidgets.QLabel(self.page_5)
        self.label_20.setStyleSheet("background-color: rgba(255, 255, 255, 200);")
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_24.addWidget(self.label_20)
        self.lcd_real_steer = QtWidgets.QLCDNumber(self.page_5)
        self.lcd_real_steer.setDigitCount(7)
        self.lcd_real_steer.setObjectName("lcd_real_steer")
        self.horizontalLayout_24.addWidget(self.lcd_real_steer)
        self.verticalLayout_23.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_18 = QtWidgets.QLabel(self.page_5)
        self.label_18.setStyleSheet("background-color: rgba(255, 255, 255, 200);")
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_23.addWidget(self.label_18)
        self.lcd_theta_e = QtWidgets.QLCDNumber(self.page_5)
        self.lcd_theta_e.setDigitCount(7)
        self.lcd_theta_e.setObjectName("lcd_theta_e")
        self.horizontalLayout_23.addWidget(self.lcd_theta_e)
        self.verticalLayout_23.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_19 = QtWidgets.QLabel(self.page_5)
        self.label_19.setStyleSheet("background-color: rgba(255, 255, 255, 200);")
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_22.addWidget(self.label_19)
        self.lcd_theta_d = QtWidgets.QLCDNumber(self.page_5)
        self.lcd_theta_d.setDigitCount(7)
        self.lcd_theta_d.setObjectName("lcd_theta_d")
        self.horizontalLayout_22.addWidget(self.lcd_theta_d)
        self.verticalLayout_23.addLayout(self.horizontalLayout_22)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_23.addItem(spacerItem4)
        self.toolBox.addItem(self.page_5, "")
        self.MiddleLayout.addWidget(self.toolBox)
        self.TabLayout = QtWidgets.QHBoxLayout()
        self.TabLayout.setObjectName("TabLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setSizeIncrement(QtCore.QSize(20, 0))
        self.tabWidget.setStyleSheet("background-color:transparent;\n"
"border-color: rgb(255, 0, 0);")
        self.tabWidget.setObjectName("tabWidget")
        self.Console = QtWidgets.QWidget()
        self.Console.setObjectName("Console")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.Console)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.console_1 = QtWidgets.QTextEdit(self.Console)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.console_1.sizePolicy().hasHeightForWidth())
        self.console_1.setSizePolicy(sizePolicy)
        self.console_1.setMinimumSize(QtCore.QSize(0, 0))
        self.console_1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.console_1.setObjectName("console_1")
        self.verticalLayout_7.addWidget(self.console_1)
        self.tabWidget.addTab(self.Console, "")
        self.lidarMap = QtWidgets.QWidget()
        self.lidarMap.setObjectName("lidarMap")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.lidarMap)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.verticalLayout_5.addLayout(self.verticalLayout_17)
        self.tabWidget.addTab(self.lidarMap, "")
        self.globalMap = QtWidgets.QWidget()
        self.globalMap.setObjectName("globalMap")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.globalMap)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.verticalLayout_9.addLayout(self.verticalLayout_19)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_7 = QtWidgets.QLabel(self.globalMap)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_13.addWidget(self.label_7)
        self.lcd_mouse_x = QtWidgets.QLCDNumber(self.globalMap)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcd_mouse_x.sizePolicy().hasHeightForWidth())
        self.lcd_mouse_x.setSizePolicy(sizePolicy)
        self.lcd_mouse_x.setObjectName("lcd_mouse_x")
        self.horizontalLayout_13.addWidget(self.lcd_mouse_x)
        self.label_8 = QtWidgets.QLabel(self.globalMap)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_13.addWidget(self.label_8)
        self.lcd_mouse_y = QtWidgets.QLCDNumber(self.globalMap)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcd_mouse_y.sizePolicy().hasHeightForWidth())
        self.lcd_mouse_y.setSizePolicy(sizePolicy)
        self.lcd_mouse_y.setObjectName("lcd_mouse_y")
        self.horizontalLayout_13.addWidget(self.lcd_mouse_y)
        self.verticalLayout_9.addLayout(self.horizontalLayout_13)
        self.tabWidget.addTab(self.globalMap, "")
        self.TabLayout.addWidget(self.tabWidget)
        self.MiddleLayout.addLayout(self.TabLayout)
        self.verticalLayout_6.addLayout(self.MiddleLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_4.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1133, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(4)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "ROVER HMI"))
        self.warring.setText(_translate("MainWindow", "Warring"))
        self.RoverMainOnOffBtn.setText(_translate("MainWindow", "Main"))
        self.VisionOnOffBtn.setText(_translate("MainWindow", "Vision"))
        self.LidarOnOffBtn.setText(_translate("MainWindow", "Lidar"))
        self.AlgorithmOnOffBtn.setText(_translate("MainWindow", "Algorithm"))
        self.StopAllBtn.setText(_translate("MainWindow", "Stop All"))
        self.label_5.setText(_translate("MainWindow", "LiDAR USB"))
        self.label.setText(_translate("MainWindow", "Vision Status"))
        self.label_4.setText(_translate("MainWindow", "Vision Data"))
        self.label_6.setText(_translate("MainWindow", "Current Speed(pwm)"))
        self.label_16.setText(_translate("MainWindow", "PP time (s)"))
        self.groupBox.setTitle(_translate("MainWindow", "Car Control"))
        self.KeyboardControlBtn.setText(_translate("MainWindow", "Keyboard Control (WASD)"))
        self.KeyboardControl_SetSpeedBtn.setText(_translate("MainWindow", "Set Speed"))
        self.SetSpeed_label.setText(_translate("MainWindow", "0"))
        self.ShowMapBtn.setText(_translate("MainWindow", "Show data and build Map"))
        self.ShowMap_AddBtn.setText(_translate("MainWindow", "Add current"))
        self.ShowMap_DelBtn.setText(_translate("MainWindow", "Delete last"))
        self.SaveMapBtn.setText(_translate("MainWindow", "Save Map"))
        self.ImportMapBtn.setText(_translate("MainWindow", "Import MAP"))
        self.WayPointsBtn.setText(_translate("MainWindow", "WayPoints"))
        self.AddWayPointBtn.setText(_translate("MainWindow", "Add"))
        self.DeleteWayPointBtn.setText(_translate("MainWindow", "Delete"))
        self.CalibrationBtn.setText(_translate("MainWindow", "Calibration"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "General"))
        self.VisionBuildMapBtn.setText(_translate("MainWindow", "Vision Build Map"))
        self.pushButton.setText(_translate("MainWindow", "Show Map List"))
        self.label_2.setText(_translate("MainWindow", "MapID"))
        self.VisionBuildMapStopBtn.setText(_translate("MainWindow", "Build Map Stop"))
        self.VisionUseMapBtn.setText(_translate("MainWindow", "Vision Use Map"))
        self.label_3.setText(_translate("MainWindow", "MapID"))
        self.VisionUseMapStopBtn.setText(_translate("MainWindow", "Use Map Stop"))
        self.pushButton_2.setText(_translate("MainWindow", "Vision Calibration"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Vision"))
        self.label_10.setText(_translate("MainWindow", "Lidar Max R(mm)"))
        self.label_9.setText(_translate("MainWindow", "Lidar Min R(mm)"))
        self.btn_set_lidar_radius.setText(_translate("MainWindow", "Set"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("MainWindow", "Lidar"))
        self.label_13.setText(_translate("MainWindow", "End X"))
        self.label_12.setText(_translate("MainWindow", "End Y"))
        self.btn_set_end.setText(_translate("MainWindow", "Set"))
        self.label_15.setText(_translate("MainWindow", "ROVER size(cm)"))
        self.label_14.setText(_translate("MainWindow", "Unit step (cm)"))
        self.btn_set_as.setText(_translate("MainWindow", "Set"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), _translate("MainWindow", "Path Planning"))
        self.label_11.setText(_translate("MainWindow", "Theta e gain"))
        self.btn_pp_gain.setText(_translate("MainWindow", "Set"))
        self.label_22.setText(_translate("MainWindow", "Theta d gain"))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton"))
        self.label_17.setText(_translate("MainWindow", "Target steer (deg)"))
        self.label_21.setText(_translate("MainWindow", "Global steer (deg)"))
        self.label_20.setText(_translate("MainWindow", "Real steer (deg)"))
        self.label_18.setText(_translate("MainWindow", "theta e (deg)"))
        self.label_19.setText(_translate("MainWindow", "theta d (deg)"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_5), _translate("MainWindow", "Path Tracking"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Console), _translate("MainWindow", "Console"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.lidarMap), _translate("MainWindow", "LiDAR"))
        self.label_7.setText(_translate("MainWindow", "X:"))
        self.label_8.setText(_translate("MainWindow", "Y:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.globalMap), _translate("MainWindow", "Vision and LiDAR Map"))

