# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rover_v3.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(874, 751)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(0, 255, 237, 69), stop:0.426471 rgba(0, 214, 138, 69), stop:0.441176 rgba(0, 255, 246, 145), stop:0.534314 rgba(255, 255, 0, 135), stop:0.57754 rgba(0, 201, 255, 130), stop:0.70098 rgba(0, 178, 171, 208), stop:0.779412 rgba(255, 218, 71, 130), stop:1 rgba(0, 237, 255, 69));")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 850, 686))
        self.scrollAreaWidgetContents_2.setStyleSheet("background-color:transparent;")
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.TopLayout = QtWidgets.QHBoxLayout()
        self.TopLayout.setObjectName("TopLayout")
        self.title = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(28)
        self.title.setFont(font)
        self.title.setStyleSheet("background-color: rgb(255, 255, 255,80%);")
        self.title.setObjectName("title")
        self.TopLayout.addWidget(self.title)
        self.warring = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(28)
        self.warring.setFont(font)
        self.warring.setStyleSheet("background-color:transparent;\n"
"background-color: rgb(255, 239, 57);")
        self.warring.setAlignment(QtCore.Qt.AlignCenter)
        self.warring.setObjectName("warring")
        self.TopLayout.addWidget(self.warring)
        self.OnOffBtnLayout = QtWidgets.QHBoxLayout()
        self.OnOffBtnLayout.setObjectName("OnOffBtnLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.BridgeOnOffBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.BridgeOnOffBtn.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.BridgeOnOffBtn.setObjectName("BridgeOnOffBtn")
        self.verticalLayout.addWidget(self.BridgeOnOffBtn)
        self.VisionOnOffBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.VisionOnOffBtn.setStyleSheet("background-color: rgb(255, 3, 3);")
        self.VisionOnOffBtn.setObjectName("VisionOnOffBtn")
        self.verticalLayout.addWidget(self.VisionOnOffBtn)
        self.OnOffBtnLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.LidarOnOffBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.LidarOnOffBtn.setStyleSheet("background-color: rgb(255, 3, 3);")
        self.LidarOnOffBtn.setObjectName("LidarOnOffBtn")
        self.verticalLayout_3.addWidget(self.LidarOnOffBtn)
        self.AlgorithmOnOffBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.AlgorithmOnOffBtn.setStyleSheet("background-color: rgb(255, 3, 3);")
        self.AlgorithmOnOffBtn.setObjectName("AlgorithmOnOffBtn")
        self.verticalLayout_3.addWidget(self.AlgorithmOnOffBtn)
        self.OnOffBtnLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.OnOffBtnLayout.addLayout(self.verticalLayout_2)
        self.StopAllBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StopAllBtn.sizePolicy().hasHeightForWidth())
        self.StopAllBtn.setSizePolicy(sizePolicy)
        self.StopAllBtn.setStyleSheet("background-color: rgb(255, 3, 3);")
        self.StopAllBtn.setObjectName("StopAllBtn")
        self.OnOffBtnLayout.addWidget(self.StopAllBtn)
        self.TopLayout.addLayout(self.OnOffBtnLayout)
        self.verticalLayout_6.addLayout(self.TopLayout)
        self.MiddleLayout = QtWidgets.QHBoxLayout()
        self.MiddleLayout.setObjectName("MiddleLayout")
        self.FunctionBtnLayout = QtWidgets.QVBoxLayout()
        self.FunctionBtnLayout.setObjectName("FunctionBtnLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.KeyboardControlBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.KeyboardControlBtn.sizePolicy().hasHeightForWidth())
        self.KeyboardControlBtn.setSizePolicy(sizePolicy)
        self.KeyboardControlBtn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.KeyboardControlBtn.setFont(font)
        self.KeyboardControlBtn.setStyleSheet("background-color: rgb(112, 155, 255);")
        self.KeyboardControlBtn.setObjectName("KeyboardControlBtn")
        self.horizontalLayout_7.addWidget(self.KeyboardControlBtn)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, -1, 0, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.KeyUp = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.KeyUp.sizePolicy().hasHeightForWidth())
        self.KeyUp.setSizePolicy(sizePolicy)
        self.KeyUp.setMaximumSize(QtCore.QSize(20, 20))
        self.KeyUp.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.KeyUp.setObjectName("KeyUp")
        self.gridLayout.addWidget(self.KeyUp, 0, 1, 1, 1)
        self.KeyRight = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.KeyRight.sizePolicy().hasHeightForWidth())
        self.KeyRight.setSizePolicy(sizePolicy)
        self.KeyRight.setMaximumSize(QtCore.QSize(20, 20))
        self.KeyRight.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.KeyRight.setObjectName("KeyRight")
        self.gridLayout.addWidget(self.KeyRight, 1, 2, 1, 1)
        self.KeyDown = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.KeyDown.sizePolicy().hasHeightForWidth())
        self.KeyDown.setSizePolicy(sizePolicy)
        self.KeyDown.setMaximumSize(QtCore.QSize(20, 20))
        self.KeyDown.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.KeyDown.setObjectName("KeyDown")
        self.gridLayout.addWidget(self.KeyDown, 1, 1, 1, 1)
        self.KeyLeft = QtWidgets.QGraphicsView(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.KeyLeft.sizePolicy().hasHeightForWidth())
        self.KeyLeft.setSizePolicy(sizePolicy)
        self.KeyLeft.setMaximumSize(QtCore.QSize(20, 20))
        self.KeyLeft.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.KeyLeft.setObjectName("KeyLeft")
        self.gridLayout.addWidget(self.KeyLeft, 1, 0, 1, 1)
        self.horizontalLayout_7.addLayout(self.gridLayout)
        self.FunctionBtnLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.VisionBuildMapBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.VisionBuildMapBtn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.VisionBuildMapBtn.setFont(font)
        self.VisionBuildMapBtn.setStyleSheet("background-color: rgb(112, 155, 255);")
        self.VisionBuildMapBtn.setObjectName("VisionBuildMapBtn")
        self.horizontalLayout_6.addWidget(self.VisionBuildMapBtn)
        self.VisionBuildMap = QtWidgets.QVBoxLayout()
        self.VisionBuildMap.setObjectName("VisionBuildMap")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255,80%);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.BuildMapID = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BuildMapID.sizePolicy().hasHeightForWidth())
        self.BuildMapID.setSizePolicy(sizePolicy)
        self.BuildMapID.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.BuildMapID.setObjectName("BuildMapID")
        self.horizontalLayout_3.addWidget(self.BuildMapID)
        self.VisionBuildMap.addLayout(self.horizontalLayout_3)
        self.BuildMapStopBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BuildMapStopBtn.sizePolicy().hasHeightForWidth())
        self.BuildMapStopBtn.setSizePolicy(sizePolicy)
        self.BuildMapStopBtn.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.BuildMapStopBtn.setObjectName("BuildMapStopBtn")
        self.VisionBuildMap.addWidget(self.BuildMapStopBtn)
        self.horizontalLayout_6.addLayout(self.VisionBuildMap)
        self.FunctionBtnLayout.addLayout(self.horizontalLayout_6)
        self.VisionUseMap = QtWidgets.QHBoxLayout()
        self.VisionUseMap.setObjectName("VisionUseMap")
        self.VisionUseMapBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.VisionUseMapBtn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.VisionUseMapBtn.setFont(font)
        self.VisionUseMapBtn.setStyleSheet("background-color: rgb(112, 155, 255);")
        self.VisionUseMapBtn.setObjectName("VisionUseMapBtn")
        self.VisionUseMap.addWidget(self.VisionUseMapBtn)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255,80%);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.UseMapID = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UseMapID.sizePolicy().hasHeightForWidth())
        self.UseMapID.setSizePolicy(sizePolicy)
        self.UseMapID.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.UseMapID.setObjectName("UseMapID")
        self.horizontalLayout_4.addWidget(self.UseMapID)
        self.verticalLayout_10.addLayout(self.horizontalLayout_4)
        self.UseMapStopBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.UseMapStopBtn.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.UseMapStopBtn.setObjectName("UseMapStopBtn")
        self.verticalLayout_10.addWidget(self.UseMapStopBtn)
        self.VisionUseMap.addLayout(self.verticalLayout_10)
        self.FunctionBtnLayout.addLayout(self.VisionUseMap)
        self.WayPoints = QtWidgets.QHBoxLayout()
        self.WayPoints.setObjectName("WayPoints")
        self.WayPointsBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.WayPointsBtn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.WayPointsBtn.setFont(font)
        self.WayPointsBtn.setStyleSheet("background-color: rgb(112, 155, 255);")
        self.WayPointsBtn.setObjectName("WayPointsBtn")
        self.WayPoints.addWidget(self.WayPointsBtn)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.AddWayPointBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddWayPointBtn.sizePolicy().hasHeightForWidth())
        self.AddWayPointBtn.setSizePolicy(sizePolicy)
        self.AddWayPointBtn.setStyleSheet("background-color: rgb(227, 227, 227);\n"
"border-color: rgb(0, 0, 0);")
        self.AddWayPointBtn.setObjectName("AddWayPointBtn")
        self.horizontalLayout.addWidget(self.AddWayPointBtn)
        self.DeleteWayPointBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DeleteWayPointBtn.sizePolicy().hasHeightForWidth())
        self.DeleteWayPointBtn.setSizePolicy(sizePolicy)
        self.DeleteWayPointBtn.setStyleSheet("background-color: rgb(227, 227, 227);\n"
"border-color: rgb(0, 0, 0);")
        self.DeleteWayPointBtn.setObjectName("DeleteWayPointBtn")
        self.horizontalLayout.addWidget(self.DeleteWayPointBtn)
        self.verticalLayout_8.addLayout(self.horizontalLayout)
        self.WayPointList = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WayPointList.sizePolicy().hasHeightForWidth())
        self.WayPointList.setSizePolicy(sizePolicy)
        self.WayPointList.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.WayPointList.setObjectName("WayPointList")
        self.verticalLayout_8.addWidget(self.WayPointList)
        self.WayPoints.addLayout(self.verticalLayout_8)
        self.FunctionBtnLayout.addLayout(self.WayPoints)
        self.SaveMap = QtWidgets.QHBoxLayout()
        self.SaveMap.setObjectName("SaveMap")
        self.SaveMapBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.SaveMapBtn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.SaveMapBtn.setFont(font)
        self.SaveMapBtn.setStyleSheet("background-color: rgb(112, 155, 255);")
        self.SaveMapBtn.setObjectName("SaveMapBtn")
        self.SaveMap.addWidget(self.SaveMapBtn)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.lineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_11.addWidget(self.lineEdit)
        self.SaveMap.addLayout(self.verticalLayout_11)
        self.FunctionBtnLayout.addLayout(self.SaveMap)
        self.ShowMapBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.ShowMapBtn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(12)
        self.ShowMapBtn.setFont(font)
        self.ShowMapBtn.setStyleSheet("background-color: rgb(112, 155, 255);")
        self.ShowMapBtn.setObjectName("ShowMapBtn")
        self.FunctionBtnLayout.addWidget(self.ShowMapBtn)
        self.Btnnnnn = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.Btnnnnn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Btnnnnn.setFont(font)
        self.Btnnnnn.setStyleSheet("background-color: rgb(112, 155, 255);")
        self.Btnnnnn.setObjectName("Btnnnnn")
        self.FunctionBtnLayout.addWidget(self.Btnnnnn)
        self.MiddleLayout.addLayout(self.FunctionBtnLayout)
        self.TabLayout = QtWidgets.QHBoxLayout()
        self.TabLayout.setObjectName("TabLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.scrollAreaWidgetContents_2)
        self.tabWidget.setStyleSheet("background-color:transparent;\n"
"border-color: rgb(255, 0, 0);")
        self.tabWidget.setObjectName("tabWidget")
        self.Console = QtWidgets.QWidget()
        self.Console.setObjectName("Console")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.Console)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.console_1 = QtWidgets.QTextEdit(self.Console)
        self.console_1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.console_1.setObjectName("console_1")
        self.verticalLayout_7.addWidget(self.console_1)
        self.tabWidget.addTab(self.Console, "")
        self.lidarMap = QtWidgets.QWidget()
        self.lidarMap.setObjectName("lidarMap")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.lidarMap)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.LidarMap = LidarMap(self.lidarMap)
        self.LidarMap.setObjectName("LidarMap")
        self.verticalLayout_5.addWidget(self.LidarMap)
        self.tabWidget.addTab(self.lidarMap, "")
        self.globalMap = QtWidgets.QWidget()
        self.globalMap.setObjectName("globalMap")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.globalMap)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.GlobalMap = GlobalMap(self.globalMap)
        self.GlobalMap.setObjectName("GlobalMap")
        self.verticalLayout_9.addWidget(self.GlobalMap)
        self.tabWidget.addTab(self.globalMap, "")
        self.TabLayout.addWidget(self.tabWidget)
        self.MiddleLayout.addLayout(self.TabLayout)
        self.verticalLayout_6.addLayout(self.MiddleLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_4.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 874, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "ROVER HMI"))
        self.warring.setText(_translate("MainWindow", "Warring"))
        self.BridgeOnOffBtn.setText(_translate("MainWindow", "Bridge"))
        self.VisionOnOffBtn.setText(_translate("MainWindow", "Vision"))
        self.LidarOnOffBtn.setText(_translate("MainWindow", "Lidar"))
        self.AlgorithmOnOffBtn.setText(_translate("MainWindow", "Algorithm"))
        self.StopAllBtn.setText(_translate("MainWindow", "Stop All"))
        self.KeyboardControlBtn.setText(_translate("MainWindow", "Keyboard Control"))
        self.VisionBuildMapBtn.setText(_translate("MainWindow", "Vision Build Map"))
        self.label_2.setText(_translate("MainWindow", "MapID"))
        self.BuildMapStopBtn.setText(_translate("MainWindow", "Build Map Stop"))
        self.VisionUseMapBtn.setText(_translate("MainWindow", "Vision Use Map"))
        self.label_3.setText(_translate("MainWindow", "MapID"))
        self.UseMapStopBtn.setText(_translate("MainWindow", "Use Map Stop"))
        self.WayPointsBtn.setText(_translate("MainWindow", "WayPoints"))
        self.AddWayPointBtn.setText(_translate("MainWindow", "Add"))
        self.DeleteWayPointBtn.setText(_translate("MainWindow", "Delete"))
        self.SaveMapBtn.setText(_translate("MainWindow", "Save Map"))
        self.ShowMapBtn.setText(_translate("MainWindow", "Show Map"))
        self.Btnnnnn.setText(_translate("MainWindow", "Future Work"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Console), _translate("MainWindow", "Console"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.lidarMap), _translate("MainWindow", "Map"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.globalMap), _translate("MainWindow", "頁面"))

from globalmap import GlobalMap
from lidarmap import LidarMap
