# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'simulator.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1041, 799)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.combo_map = QtWidgets.QComboBox(self.centralwidget)
        self.combo_map.setEditable(False)
        self.combo_map.setCurrentText("")
        self.combo_map.setObjectName("combo_map")
        self.horizontalLayout.addWidget(self.combo_map)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_7.addWidget(self.label_5)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_12.addWidget(self.label_10)
        self.spin_start_x = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_start_x.setMinimum(-100000)
        self.spin_start_x.setMaximum(100000)
        self.spin_start_x.setObjectName("spin_start_x")
        self.horizontalLayout_12.addWidget(self.spin_start_x)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_14.addWidget(self.label_9)
        self.spin_start_y = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_start_y.setMinimum(-100000)
        self.spin_start_y.setMaximum(100000)
        self.spin_start_y.setObjectName("spin_start_y")
        self.horizontalLayout_14.addWidget(self.spin_start_y)
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_9.addLayout(self.verticalLayout_6)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_10.addWidget(self.label_7)
        self.spin_end_x = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_end_x.setMinimum(-100000)
        self.spin_end_x.setMaximum(100000)
        self.spin_end_x.setObjectName("spin_end_x")
        self.horizontalLayout_10.addWidget(self.spin_end_x)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_11.addWidget(self.label_8)
        self.spin_end_y = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_end_y.setMinimum(-100000)
        self.spin_end_y.setMaximum(100000)
        self.spin_end_y.setObjectName("spin_end_y")
        self.horizontalLayout_11.addWidget(self.spin_end_y)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_9.addLayout(self.verticalLayout_5)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_23.addWidget(self.label_18)
        self.spin_start_yaw = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_start_yaw.setMaximum(360)
        self.spin_start_yaw.setObjectName("spin_start_yaw")
        self.horizontalLayout_23.addWidget(self.spin_start_yaw)
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_23.addWidget(self.label_17)
        self.spin_end_yaw = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_end_yaw.setMaximum(360)
        self.spin_end_yaw.setObjectName("spin_end_yaw")
        self.horizontalLayout_23.addWidget(self.spin_end_yaw)
        self.verticalLayout_7.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_17.addWidget(self.label_13)
        self.spin_rover_radius = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_rover_radius.setMinimum(30)
        self.spin_rover_radius.setMaximum(1000)
        self.spin_rover_radius.setObjectName("spin_rover_radius")
        self.horizontalLayout_17.addWidget(self.spin_rover_radius)
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_17.addWidget(self.label_14)
        self.spin_safe_radius = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_safe_radius.setMinimum(1)
        self.spin_safe_radius.setMaximum(500)
        self.spin_safe_radius.setProperty("value", 1)
        self.spin_safe_radius.setObjectName("spin_safe_radius")
        self.horizontalLayout_17.addWidget(self.spin_safe_radius)
        self.verticalLayout_7.addLayout(self.horizontalLayout_17)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.radio_a_v2 = QtWidgets.QRadioButton(self.groupBox)
        self.radio_a_v2.setChecked(True)
        self.radio_a_v2.setObjectName("radio_a_v2")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radio_a_v2)
        self.horizontalLayout_19.addWidget(self.radio_a_v2)
        self.radio_a_v3 = QtWidgets.QRadioButton(self.groupBox)
        self.radio_a_v3.setChecked(False)
        self.radio_a_v3.setObjectName("radio_a_v3")
        self.buttonGroup.addButton(self.radio_a_v3)
        self.horizontalLayout_19.addWidget(self.radio_a_v3)
        self.radio_original_a = QtWidgets.QRadioButton(self.groupBox)
        self.radio_original_a.setChecked(False)
        self.radio_original_a.setObjectName("radio_original_a")
        self.buttonGroup.addButton(self.radio_original_a)
        self.horizontalLayout_19.addWidget(self.radio_original_a)
        self.verticalLayout_7.addWidget(self.groupBox)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_15.addWidget(self.label_11)
        self.dspin_hcost = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.dspin_hcost.setMinimum(0.01)
        self.dspin_hcost.setProperty("value", 1.0)
        self.dspin_hcost.setObjectName("dspin_hcost")
        self.horizontalLayout_15.addWidget(self.dspin_hcost)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_15.addWidget(self.label_12)
        self.dspin_gcost = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.dspin_gcost.setMinimum(0.01)
        self.dspin_gcost.setProperty("value", 0.5)
        self.dspin_gcost.setObjectName("dspin_gcost")
        self.horizontalLayout_15.addWidget(self.dspin_gcost)
        self.verticalLayout_7.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_8.addWidget(self.label_15)
        self.spin_unitstep = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_unitstep.setMinimum(1)
        self.spin_unitstep.setMaximum(400)
        self.spin_unitstep.setProperty("value", 60)
        self.spin_unitstep.setObjectName("spin_unitstep")
        self.horizontalLayout_8.addWidget(self.spin_unitstep)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.check_pxmode = QtWidgets.QCheckBox(self.centralwidget)
        self.check_pxmode.setCheckable(True)
        self.check_pxmode.setChecked(True)
        self.check_pxmode.setAutoRepeat(False)
        self.check_pxmode.setAutoExclusive(False)
        self.check_pxmode.setObjectName("check_pxmode")
        self.horizontalLayout_16.addWidget(self.check_pxmode)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.check_progress = QtWidgets.QCheckBox(self.centralwidget)
        self.check_progress.setObjectName("check_progress")
        self.horizontalLayout_13.addWidget(self.check_progress)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_13)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_18.addWidget(self.label_16)
        self.lcd_astar_planning_time = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_astar_planning_time.setObjectName("lcd_astar_planning_time")
        self.horizontalLayout_18.addWidget(self.lcd_astar_planning_time)
        self.verticalLayout_7.addLayout(self.horizontalLayout_18)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.radio_bspline = QtWidgets.QRadioButton(self.groupBox_2)
        self.radio_bspline.setChecked(True)
        self.radio_bspline.setObjectName("radio_bspline")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.radio_bspline)
        self.horizontalLayout_20.addWidget(self.radio_bspline)
        self.radio_cubic_spline = QtWidgets.QRadioButton(self.groupBox_2)
        self.radio_cubic_spline.setObjectName("radio_cubic_spline")
        self.buttonGroup_2.addButton(self.radio_cubic_spline)
        self.horizontalLayout_20.addWidget(self.radio_cubic_spline)
        self.verticalLayout_7.addWidget(self.groupBox_2)
        self.groupBox_test_tracking = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_test_tracking.setCheckable(True)
        self.groupBox_test_tracking.setChecked(False)
        self.groupBox_test_tracking.setObjectName("groupBox_test_tracking")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_test_tracking)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_21 = QtWidgets.QLabel(self.groupBox_test_tracking)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_25.addWidget(self.label_21)
        self.spin_control_gain = QtWidgets.QSpinBox(self.groupBox_test_tracking)
        self.spin_control_gain.setObjectName("spin_control_gain")
        self.horizontalLayout_25.addWidget(self.spin_control_gain)
        self.label_22 = QtWidgets.QLabel(self.groupBox_test_tracking)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_25.addWidget(self.label_22)
        self.spin_current_yaw = QtWidgets.QSpinBox(self.groupBox_test_tracking)
        self.spin_current_yaw.setObjectName("spin_current_yaw")
        self.horizontalLayout_25.addWidget(self.spin_current_yaw)
        self.verticalLayout_4.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_19 = QtWidgets.QLabel(self.groupBox_test_tracking)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_24.addWidget(self.label_19)
        self.lcd_steering_agnle = QtWidgets.QLCDNumber(self.groupBox_test_tracking)
        self.lcd_steering_agnle.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_steering_agnle.setObjectName("lcd_steering_agnle")
        self.horizontalLayout_24.addWidget(self.lcd_steering_agnle)
        self.label_20 = QtWidgets.QLabel(self.groupBox_test_tracking)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_24.addWidget(self.label_20)
        self.lcd_target_index = QtWidgets.QLCDNumber(self.groupBox_test_tracking)
        self.lcd_target_index.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_target_index.setObjectName("lcd_target_index")
        self.horizontalLayout_24.addWidget(self.lcd_target_index)
        self.verticalLayout_4.addLayout(self.horizontalLayout_24)
        self.verticalLayout_7.addWidget(self.groupBox_test_tracking)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.check_show_lidar = QtWidgets.QCheckBox(self.centralwidget)
        self.check_show_lidar.setObjectName("check_show_lidar")
        self.horizontalLayout_22.addWidget(self.check_show_lidar)
        self.verticalLayout_7.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.spin_time_delay = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_time_delay.setMinimum(1)
        self.spin_time_delay.setMaximum(2000)
        self.spin_time_delay.setProperty("value", 10)
        self.spin_time_delay.setObjectName("spin_time_delay")
        self.horizontalLayout_7.addWidget(self.spin_time_delay)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_21.addLayout(self.verticalLayout_7)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.button_start = QtWidgets.QPushButton(self.centralwidget)
        self.button_start.setObjectName("button_start")
        self.horizontalLayout_4.addWidget(self.button_start)
        self.button_pause = QtWidgets.QPushButton(self.centralwidget)
        self.button_pause.setObjectName("button_pause")
        self.horizontalLayout_4.addWidget(self.button_pause)
        self.button_reset = QtWidgets.QPushButton(self.centralwidget)
        self.button_reset.setObjectName("button_reset")
        self.horizontalLayout_4.addWidget(self.button_reset)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.plot_widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_widget.sizePolicy().hasHeightForWidth())
        self.plot_widget.setSizePolicy(sizePolicy)
        self.plot_widget.setObjectName("plot_widget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.plot_widget)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addWidget(self.plot_widget)
        self.horizontalLayout_21.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.lcd_mouse_x = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcd_mouse_x.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcd_mouse_x.sizePolicy().hasHeightForWidth())
        self.lcd_mouse_x.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.lcd_mouse_x.setFont(font)
        self.lcd_mouse_x.setStyleSheet("color: rgb(8, 12, 89);\n"
"background-color: rgb(255, 255, 255);")
        self.lcd_mouse_x.setDigitCount(5)
        self.lcd_mouse_x.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_mouse_x.setProperty("value", 0.0)
        self.lcd_mouse_x.setObjectName("lcd_mouse_x")
        self.horizontalLayout_2.addWidget(self.lcd_mouse_x)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lcd_mouse_y = QtWidgets.QLCDNumber(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcd_mouse_y.sizePolicy().hasHeightForWidth())
        self.lcd_mouse_y.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.lcd_mouse_y.setFont(font)
        self.lcd_mouse_y.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lcd_mouse_y.setDigitCount(5)
        self.lcd_mouse_y.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd_mouse_y.setObjectName("lcd_mouse_y")
        self.horizontalLayout_2.addWidget(self.lcd_mouse_y)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1041, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "LAB931 ROVER Simulator"))
        self.label_2.setText(_translate("MainWindow", "Map :"))
        self.label_5.setText(_translate("MainWindow", "Start/End Position"))
        self.label_10.setText(_translate("MainWindow", "Start X:"))
        self.label_9.setText(_translate("MainWindow", "Start Y:"))
        self.label_7.setText(_translate("MainWindow", "End X:"))
        self.label_8.setText(_translate("MainWindow", "End Y:"))
        self.label_18.setText(_translate("MainWindow", "Start Yaw(deg)"))
        self.label_17.setText(_translate("MainWindow", "End Yaw(deg)"))
        self.label_13.setText(_translate("MainWindow", "ROVER Size Radius(cm)"))
        self.label_14.setText(_translate("MainWindow", "Obstacle Safe Radius(cm)"))
        self.groupBox.setTitle(_translate("MainWindow", "Algorithm : "))
        self.radio_a_v2.setText(_translate("MainWindow", "A* v2"))
        self.radio_a_v3.setText(_translate("MainWindow", "A* v3"))
        self.radio_original_a.setText(_translate("MainWindow", "Original A*"))
        self.label_11.setText(_translate("MainWindow", "H Cost Factor"))
        self.label_12.setText(_translate("MainWindow", "G Cost Factor"))
        self.label_15.setText(_translate("MainWindow", "Unit step"))
        self.check_pxmode.setText(_translate("MainWindow", "PxMode On/Off"))
        self.check_progress.setText(_translate("MainWindow", "Show Progress"))
        self.label_16.setText(_translate("MainWindow", "A* planning time : "))
        self.groupBox_2.setTitle(_translate("MainWindow", "Curve Fitting"))
        self.radio_bspline.setText(_translate("MainWindow", "Bspline"))
        self.radio_cubic_spline.setText(_translate("MainWindow", "Cubic Spline"))
        self.groupBox_test_tracking.setTitle(_translate("MainWindow", "Test tracking"))
        self.label_21.setText(_translate("MainWindow", "Control gain"))
        self.label_22.setText(_translate("MainWindow", "Current Yaw"))
        self.label_19.setText(_translate("MainWindow", "steering angle(deg)"))
        self.label_20.setText(_translate("MainWindow", "Target index"))
        self.check_show_lidar.setText(_translate("MainWindow", "Show Lidar Obstacle"))
        self.label_6.setText(_translate("MainWindow", "Time delay (1~2000 ms)"))
        self.button_start.setText(_translate("MainWindow", "Start"))
        self.button_pause.setText(_translate("MainWindow", "Pause"))
        self.button_reset.setText(_translate("MainWindow", "Reset"))
        self.label_4.setText(_translate("MainWindow", "Mouse X"))
        self.label_3.setText(_translate("MainWindow", "Mouse Y:"))

