# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rover.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1035, 701)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.console_1 = QtWidgets.QTextEdit(self.centralwidget)
        self.console_1.setGeometry(QtCore.QRect(460, 120, 381, 521))
        self.console_1.setObjectName("console_1")
        self.Title = QtWidgets.QLabel(self.centralwidget)
        self.Title.setGeometry(QtCore.QRect(10, 0, 241, 61))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(20)
        self.Title.setFont(font)
        self.Title.setTextFormat(QtCore.Qt.PlainText)
        self.Title.setScaledContents(False)
        self.Title.setObjectName("Title")
        self.EmergencyStopBtn = QtWidgets.QPushButton(self.centralwidget)
        self.EmergencyStopBtn.setGeometry(QtCore.QRect(770, 0, 261, 111))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(14)
        self.EmergencyStopBtn.setFont(font)
        self.EmergencyStopBtn.setMouseTracking(False)
        self.EmergencyStopBtn.setAutoFillBackground(False)
        self.EmergencyStopBtn.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0.011, stop:1 rgba(255, 0, 0, 255));")
        self.EmergencyStopBtn.setObjectName("EmergencyStopBtn")
        self.BridgeConnectionView = QtWidgets.QGraphicsView(self.centralwidget)
        self.BridgeConnectionView.setGeometry(QtCore.QRect(250, 80, 31, 31))
        self.BridgeConnectionView.setStyleSheet("background-color: rgb(255, 3, 3);")
        self.BridgeConnectionView.setObjectName("BridgeConnectionView")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 171, 31))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 120, 171, 31))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 160, 171, 31))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.LidarConnectionView = QtWidgets.QGraphicsView(self.centralwidget)
        self.LidarConnectionView.setGeometry(QtCore.QRect(250, 120, 31, 31))
        self.LidarConnectionView.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.LidarConnectionView.setObjectName("LidarConnectionView")
        self.VisionView = QtWidgets.QGraphicsView(self.centralwidget)
        self.VisionView.setGeometry(QtCore.QRect(250, 160, 31, 31))
        self.VisionView.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.VisionView.setObjectName("VisionView")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 200, 171, 31))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.MotorView = QtWidgets.QGraphicsView(self.centralwidget)
        self.MotorView.setGeometry(QtCore.QRect(250, 200, 31, 31))
        self.MotorView.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.MotorView.setObjectName("MotorView")
        self.KeyboardControlBtn = QtWidgets.QPushButton(self.centralwidget)
        self.KeyboardControlBtn.setGeometry(QtCore.QRect(20, 290, 201, 71))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(14)
        self.KeyboardControlBtn.setFont(font)
        self.KeyboardControlBtn.setObjectName("KeyboardControlBtn")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 240, 211, 31))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.AlgorithmView = QtWidgets.QGraphicsView(self.centralwidget)
        self.AlgorithmView.setGeometry(QtCore.QRect(250, 240, 31, 31))
        self.AlgorithmView.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.AlgorithmView.setObjectName("AlgorithmView")
        self.BuildMapBtn = QtWidgets.QPushButton(self.centralwidget)
        self.BuildMapBtn.setGeometry(QtCore.QRect(20, 370, 201, 71))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(14)
        self.BuildMapBtn.setFont(font)
        self.BuildMapBtn.setObjectName("BuildMapBtn")
        self.GetLidarDataBtn = QtWidgets.QPushButton(self.centralwidget)
        self.GetLidarDataBtn.setGeometry(QtCore.QRect(20, 450, 201, 71))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(14)
        self.GetLidarDataBtn.setFont(font)
        self.GetLidarDataBtn.setObjectName("GetLidarDataBtn")
        self.GetLidarDataBtn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.GetLidarDataBtn_2.setGeometry(QtCore.QRect(860, 190, 171, 61))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(10)
        self.GetLidarDataBtn_2.setFont(font)
        self.GetLidarDataBtn_2.setObjectName("GetLidarDataBtn_2")
        self.GetLidarDataBtn_3 = QtWidgets.QPushButton(self.centralwidget)
        self.GetLidarDataBtn_3.setGeometry(QtCore.QRect(860, 120, 171, 61))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(10)
        self.GetLidarDataBtn_3.setFont(font)
        self.GetLidarDataBtn_3.setObjectName("GetLidarDataBtn_3")
        self.GetLidarDataBtn_4 = QtWidgets.QPushButton(self.centralwidget)
        self.GetLidarDataBtn_4.setGeometry(QtCore.QRect(860, 260, 171, 61))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(10)
        self.GetLidarDataBtn_4.setFont(font)
        self.GetLidarDataBtn_4.setObjectName("GetLidarDataBtn_4")
        self.GetLidarDataBtn_5 = QtWidgets.QPushButton(self.centralwidget)
        self.GetLidarDataBtn_5.setGeometry(QtCore.QRect(860, 330, 171, 61))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(10)
        self.GetLidarDataBtn_5.setFont(font)
        self.GetLidarDataBtn_5.setObjectName("GetLidarDataBtn_5")
        self.GetLidarDataBtn_6 = QtWidgets.QPushButton(self.centralwidget)
        self.GetLidarDataBtn_6.setGeometry(QtCore.QRect(860, 400, 171, 61))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(10)
        self.GetLidarDataBtn_6.setFont(font)
        self.GetLidarDataBtn_6.setObjectName("GetLidarDataBtn_6")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(300, 380, 51, 21))
        self.spinBox.setObjectName("spinBox")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 380, 58, 15))
        self.label.setObjectName("label")
        self.Key_up = QtWidgets.QGraphicsView(self.centralwidget)
        self.Key_up.setGeometry(QtCore.QRect(270, 300, 21, 21))
        self.Key_up.setStyleSheet("")
        self.Key_up.setObjectName("Key_up")
        self.Key_right = QtWidgets.QGraphicsView(self.centralwidget)
        self.Key_right.setGeometry(QtCore.QRect(300, 330, 21, 21))
        self.Key_right.setStyleSheet("")
        self.Key_right.setObjectName("Key_right")
        self.Key_left = QtWidgets.QGraphicsView(self.centralwidget)
        self.Key_left.setGeometry(QtCore.QRect(240, 330, 21, 21))
        self.Key_left.setStyleSheet("")
        self.Key_left.setObjectName("Key_left")
        self.Key_down = QtWidgets.QGraphicsView(self.centralwidget)
        self.Key_down.setGeometry(QtCore.QRect(270, 330, 21, 21))
        self.Key_down.setStyleSheet("")
        self.Key_down.setObjectName("Key_down")
        self.GetLidarDataBtn_7 = QtWidgets.QPushButton(self.centralwidget)
        self.GetLidarDataBtn_7.setGeometry(QtCore.QRect(20, 530, 201, 71))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(14)
        self.GetLidarDataBtn_7.setFont(font)
        self.GetLidarDataBtn_7.setObjectName("GetLidarDataBtn_7")
        self.WayPointList = QtWidgets.QListView(self.centralwidget)
        self.WayPointList.setGeometry(QtCore.QRect(230, 570, 201, 31))
        self.WayPointList.setObjectName("WayPointList")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1035, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Title.setText(_translate("MainWindow", "ROVER HMI"))
        self.EmergencyStopBtn.setText(_translate("MainWindow", "Emergency Stop"))
        self.label_2.setText(_translate("MainWindow", "Bridge Connection"))
        self.label_3.setText(_translate("MainWindow", "LiDAR Connection"))
        self.label_4.setText(_translate("MainWindow", "Vision Connection"))
        self.label_5.setText(_translate("MainWindow", "Motor Connection"))
        self.KeyboardControlBtn.setText(_translate("MainWindow", "KeyBoard control"))
        self.label_6.setText(_translate("MainWindow", "Algorithm Connection"))
        self.BuildMapBtn.setText(_translate("MainWindow", "Build map"))
        self.GetLidarDataBtn.setText(_translate("MainWindow", "Get LiDAR data"))
        self.GetLidarDataBtn_2.setText(_translate("MainWindow", "LiDAR On/Off"))
        self.GetLidarDataBtn_3.setText(_translate("MainWindow", "Bridge On/Off"))
        self.GetLidarDataBtn_4.setText(_translate("MainWindow", "Vision On/Off"))
        self.GetLidarDataBtn_5.setText(_translate("MainWindow", "Motor On/Off"))
        self.GetLidarDataBtn_6.setText(_translate("MainWindow", "Algorithm On/Off"))
        self.label.setText(_translate("MainWindow", "Map ID :"))
        self.GetLidarDataBtn_7.setText(_translate("MainWindow", "WayPointMode"))

